spring:
  application:
    name: eams
# 디폴트 환경
# 접속 정보 jasypt 적용.
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # sql log 출력
    properties:
      hibernate:
        format_sql: true # sql log 가독성 좋게 출력

#  SSR 타임리프 템플릿 설정.
  thymeleaf:
#    대체로 디폴트 설정 그대로. 개발 중 캐시는 false.
    cache: false

server:
#  port: 8080 # 디폴트 값 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: JSESSIONID_EAMS # 디폴트 세션쿠키명 JSESSIONID 쓰면 별개 세션과 중복 가능성 있음
    context-path: /hblee-pf1/



---
# 환경분리. 별도로 명시하지 않은 설정은 디폴트와 동일.
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none

